### ISSUE TITLE
Touch Screen, Mouse, and Keyboard not working after installing driver

### ISSUE THREAD

**Issue by cbayles1** [UCTRONICS/UCTRONICS_LCD35_HDMI_RPI#1]
Hi, so I recently bought this UCTRONICS LCD 3.5 in. for the Raspberry Pi, and attaching it and getting it to turn on worked just fine. I installed the driver (from this GitHub, using the instructions that came with the screen) using a TV monitor, as well as a keyboard and mouse. The keyboard and mouse worked fine as I did that. I installed the driver properly, and then unplugged the HDMI cord connecting the Pi to the TV and plugged the touch screen into the Pi. The desktop appeared properly, with the correct resolution, but I tried touching the screen with both my finger and the stylus, and neither one would work. I tried moving the mouse, which was still connected, and it didn't do anything. I tried pressing Tab, Enter, etc. on the keyboard, hoping it would navigate the desktop, but to no avail. Next, I tried plugging the Pi back into the TV monitor, and it said something about the resolution being incorrect, and nothing would show up on the TV. I realized I could probably reinstall or uninstall the driver via SSH from my other computer, but after trying, I can confirm that SSH is not enabled on the Pi, meaning that won't work. I tried restarting the Pi a few times, but I forgot at what points I did so. 
My only thought is to reinstall Raspbian, but I wanted to make sure I couldn't solve the problem in an easier way first. 
If you have any ideas that might help, I would appreciate it greatly. Thanks!

**Comment by blackbool44** [comment]
Hi, 

I have exactly the same issue for an install on a raspberry with octoprint instance.

Thanks a lot
